scality/ScalitySproxydSwift

swift_scality_backend/diskfile.py

Our DiskFileReader class doesn't try to do data integrity
checks so no need to build a DiskFileReader instance with
Etag and Content-Lenght parameter

Remove unused vars from DiskFileReader's constructor

---

swift_scality_backend/diskfile.py
swift_scality_backend/utils.py
test/unit/test_utils.py

is_sproxyd_conf_valid() should now works with both INI and JSON
configuration.
We drop the checks on the by_path_cos and by_path_serviceid because
these checks are already done by sproxyd itself.
Closes #36

Make is_sproxyd_conf_valid() independent from the config format

---

requirements.txt
setup.py
swift_scality_backend/__init__.py
swift_scality_backend/diskfile.py
swift_scality_backend/http_utils.py
swift_scality_backend/utils.py
test-requirements.txt
test/unit/test_diskfile.py
test/unit/test_utils.py

The `DiskFileWriter` and `DiskFileReader::zero_copy_send` still
use non pooled HTTP connection.
Closes #37

Use HTTP connections pool

---

tox.ini

This needs an executable named python2.6 in $PATH. For Ubuntu based
system, this PPA has been tested : ppa:fkrull/deadsnakes

Add a py26-1.13 tox target

---

test/unit/test_diskfile.py

New versions of `pep8` introduce new checks. Fix one of those.

Fixup PEP8 error

---

setup.py

This should only be used on development branches. Right before a release
(on some release branch), the version must be set to a fixed string.

Set package version based on Git data

---

setup.py

The changes introduced in 00a95a87 broke `tox` runs because these rely
on source packages. This commit works around by supporting non-Git
trees, setting the version to '999' unconditionally.
See: 00a95a87cee314fe25df41dc039dc09de794a91f

Work-around missing Git repository during Tox runs

---

test/unit/test_utils.py

This value is arbitrarily set but should be long enough to let
the failure detector detects the host went down and up again several
times.
The previous value, 0.1 sec, was not enough.

Increase the sleep time in `test_monitoring_loop_with_ping_flapping`

---

swift_scality_backend/diskfile.py
swift_scality_backend/server.py
test/unit/test_diskfile.py

The SproxydFileSystem should not contain Swift specific stuff. This commit
decouples the 2 projects.
A DiskFileManager class is created to hold config values common to every
DiskFile* instances.

Move splice detection out of SproxydFileSystem

---

tox.ini

Actually I don't understand why is that even necessary : the 'py**-swifthead' are not even on that list, still these envs can be setup by jenkins.
Actually I might clean that a little bit using http://tox.readthedocs.org/en/latest/example/basic.html#compressing-dependency-matrix

Add py26-swift2.2.0 target.

---

test/unit/test_sproxyd_client.py
test/unit/test_utils.py

This should make tests behave better.

Mock more `eventlet.sleep` calls and increase some timeouts

---

setup.py
swift_scality_backend/cli.py
swift_scality_backend/policy_configuration.py
test/unit/test_cli.py
test/unit/utils.py

Lint valid file:
```
$ swift-scality-backend storage-policy-lint --config scality-storage-policy.ini
$ echo $?
0
```
Query valid file:
```
$ swift-scality-backend storage-policy-query --config scality-storage-policy.ini read 1 sfo paris
Query
-----
Policy index: 1
Action: read
Location hints: ['sfo', 'paris']
Result
------
0: ['http://sfo1.int/arc6+3']
1: ['http://paris1.int/arc6+3', 'http://paris2.int/arc6+3']
```
Lint invalid file:
```
$ echo '[ring:invalid]' | swift-scality-backend storage-policy-lint -c -
Configuration error: Section 'ring:invalid' lacks a 'location' setting
$ echo $?
1
```
Default configuration file is `SWIFT_DIR/scality-storage-policies.ini`.

Implement storage policy configuration lint and query tool

---

swift_scality_backend/http_utils.py
test/unit/test_http_utils.py

Python 2.6 httlib.HTTPResponse does not accept a 'buffering' argument
Closes #84

0.3 py26 httplib

---

swift_scality_backend/http_utils.py
test/unit/test_http_utils.py

Our code expect a fileno method available on HTTPResponse object : 
https://github.com/scality/ScalitySproxydSwift/blob/0.3/swift_scality_backend/diskfile.py#L405
The fileno method on httplib.HTTPResponse is only available starting py27.

Implement fileno method for py26 compatibility.

---

swift_scality_backend/server.py
test/unit/test_server.py

Fix `sproxyd_timeout` not being cast as `float`

---

swift_scality_backend/server.py
test/unit/test_server.py

Sproxyd client expects `conn_timeout` not `sproxyd_conn_timeout`.
Bug introduced with commit a3bc35b151e5b40060e38669395bfd9e503162cb

Fix wrong SproxydClient arguments name

---

swift_scality_backend/diskfile.py
swift_scality_backend/server.py
test/unit/test_server.py

* A `commit` method has been added to the DiskFileWriter which is a no-op
except for the EC diskfile.
* The `policy_index` and `policy_idx` arguments in the Object server classe
have been renamed to `policy`
Closes: #106

Support Swift 2.3

---

swift_scality_backend/http_utils.py
tox.ini

A swift functional test run revealed that http_utils.py is crashing with old versions of eventlet, because we are relying on eventlet's last version package layout.
This PR correct the bug and add a dependency on eventlet==0.9.15 for the swift1.13.1 factor in the tox environment configuration, so that the unit tests not only runs with the latest eventlet version, which was the case before.
We chose 0.9.15 because swift1.13.1 requires eventlet >=0.9.15.

Eventlet backward compatibility

---

jenkins/swift-functional-tests/30-run-tests.sh

By default `nose` only outputs some dots on a single line, and Jenkins seems to use line-buffering, so the console output isn't updated whilst tests are running.
This commit adds the `-v` flag to the `nosetests` call so it prints which test is being executed, and some intermediate results.

CI: Enable verbose execution mode in functional tests

---

doc/installation.rst
swift_scality_backend/diskfile.py
test/unit/test_diskfile.py

This change is required to properly distinguish object names
'ob/j' from object named 'ob//j'. Indeed, some webservers such as
Apache (wrongly ?) mangle consecutive forward slahes. This change
makes sure we properly quote special URL chars.
Fixes #100

Properly escape account, container and object names

---

jenkins/swift-functional-tests/10-install-ring.sh

We need to perform run the swift-functional-tests job with AllowEncodedSlashes set independently on Ubuntu and Centos.

The AllowEncodedSlashes directive need different value depending on OS

---

swift_scality_backend/diskfile.py
test/unit/test_ranges.py

This is a test for outgoing headers to sproxyd from the object server on a partial get of an object. The test works by bringing up a swift proxy and a mocked sproxyd. GET requests for partial objects are sent to the swift proxy and expected headers are checked for at the mocked sproxyd.

HTTP Range header test 

---

jenkins/swift-functional-tests/extras.d/55-swift-sproxyd.sh
requirements.txt
tox.ini

To reduce the number of accidental installations of whatever Swift release we point to in `requirements.txt`, this commit removes it altogether, whilst keeping the dependencies.
When running `pip -r requirements.txt` on a system where Swift or scality-sproxyd-client are not installed, this will result in an error and require manual installation.

Remove 'magic' `swift` and `scality-sproxyd-client` installation

---

jenkins/install-deps.sh

Try to work around issues like https://37.187.159.67:5443/job/swift-tox/320/TOXENV=py27-swift1.13.1,host=ubuntu14-large/console

CI: Explicitly install GCC on Ubuntu

---

jenkins/swift-functional-tests/20-install-openstack.sh

Since the release of oslo.i18n 2.0.0 (wich got away from the global solo namespace), the functional test job is failing on icehouse during devstack installation.
This pre-install the highest oslo.i18n but below 2.0.0.
A run : https://37.187.159.67:5443/job/swift-functional-tests/188/

Force oslo.i18n < 2.0.0 wich breaks backward compatibility

---

jenkins/swift-functional-tests/20-install-openstack.sh

Forward port to master of https://github.com/scality/ScalitySproxydSwift/pull/141
A run : https://37.187.159.67:5443/job/swift-functional-tests/191/ which gives 1403 errors.
A previous run on master (https://37.187.159.67:5443/job/swift-functional-tests/186/) gave 1331 errors but with failures on icehouse for each OS, so it is ok that the error number increases.

0.3 for master

---

jenkins/swift-functional-tests/20-install-openstack.sh
jenkins/swift-functional-tests/extras.d/55-swift-sproxyd.sh

Backport to 0.3 of https://github.com/scality/ScalitySproxydSwift/pull/130
A run : https://37.187.159.67:5443/job/swift-functional-tests/196/, with only 19 errors on each release/os which is pretty low these days.

Fix installation of Openstack trunk on Precise and Icehouse on Centos

---

swift_scality_backend/server.py

This patch adds info-level logging for the configuration retrieved at load-time, and whenever a storage policy is used for the first time. This should ease debugging configuration issues.
Proposed by @cazino.

Log configuration at load time

---

jenkins/swift-functional-tests/10-install-ring.sh

A run : https://37.187.159.67:5443/job/swift-functional-tests/198/ 19 errors per OS/Stack versions

Let the ring-install library handle Apache KeepAlive directive

---

jenkins/install-deps.sh
test-requirements.txt
tox.ini

Add swit-2.3.0 target
Avoid to install anything except flake8 which is the only thing needed in the pep8 env
(this is how Swift does it : https://github.com/openstack/swift/blob/49e7c25876cf4d3bc9412443f881e8472e88e827/tox.ini)
Mock 1.1 (latest version as the time of writing) dropped py26 compatibility.
Can't have mock dependency both in test-requirements.txt and tox.ini,
otherwise pip crashes with 'Double requirement given' error.
That might be fixed in a future version of pip :
see https://github.com/pypa/pip/issues/56
and https://github.com/pypa/pip/issues/988

Fix tox job

---

swift_scality_backend/server.py

Recent Swift versions updated the `async_update` prototype. This commit
brings our implementation back up-to-date.

Sync `async_update` API

---

tox.ini

When using Swift 2.3.0, a non-working version of PyECLib tends to be
pulled from PyPI. This patch pins the dependency version to what's
pinned in the OpenStack Kilo release.

Pin PyECLib version for Swift 2.3.0 tests

---

.coveragerc

New versions of `coverage` don't like the `ignore-errors` setting::
coverage.misc.CoverageException: Unrecognized option '[report]
ignore-errors=' in config file .coveragerc
Remove it accordingly.

Handle recent `coverage` versions

---

jenkins/swift-functional-tests/40-run-tempest-tests.sh
jenkins/swift-functional-tests/extras.d/55-swift-sproxyd.sh

This fixes the swift functional tests on juno and kilo (17 errors which are the usual ones in our 0.3 branch due to our '/' in object name problem).
Working on the master branch is another topic : devstack guys are working on using keystone v3 API, currently this leads many credential errors which will hopefully gets solved when devstack v3 support gets stabilized.
https://37.187.159.67:5443/job/swift-functional-tests/218/

Fix swift functional tests

---

jenkins/swift-functional-tests/00-variables-check.sh

The default value for the `keepalive` variable is now set by the
install_ring lib itself.

Func tests: don"t expect the `keepalive` ENV var to be set

---

jenkins/swift-functional-tests/10-install-ring.sh
jenkins/swift-functional-tests/40-run-tempest-tests.sh
jenkins/swift-functional-tests/extras.d/55-swift-sproxyd.sh

CI Swift functional tests were in very bad shape lately (hundred of errors on each run), due to the migration of devstack to keystone v3.
This introduces some stability in Juno and Kilo, even though some tests are still failing : https://37.187.159.67:5443/job/swift-functional-tests/223/.
Master should be investigated in another PR.

Fix swift functional tests for master

---

jenkins/swift-functional-tests/40-run-tempest-tests.sh
swift_scality_backend/diskfile.py
test/unit/test_diskfile.py

Our diskFile now raises a DiskFileExpired exception if it tries
to open an expired object.
The object-expirer daemon is in charge of actually deleting the expired
objects.

Support Expiring Objects

---

circle.yml

This is required to build PyECLIB

CircleCI: pre-install liberasurecode

---

doc/index.rst
doc/installation.rst
doc/misc.rst
jenkins/swift-functional-tests/10-install-ring.sh
swift_scality_backend/diskfile.py
test/scenario/multi-backend/fabfile/bootstrap.py
test/unit/test_diskfile.py

With this, no need to change the Apache config flag 'AllowEncodedSlahes'
and we also get consistent behavior with all web servers.
Warning: this is completely backward incompatible. No Swift object put before
this commit will be reachable once this patch is merged. Users of the 0.3
branch of this project should do a full copy of their Swift cluster if they
want to migrate to this branch.

Hash the account, container and object name

---

tox.ini

It seems eventlet>=0.9.15 (from requirements.txt) is enough. Not need for
exactly 0.9.15.

Tox.ini, Swift 1.13 target: remove requirement on eventlet=0.9.15

---

swift_scality_backend/server.py

In Swift `master`, the prototype of the `REQUEST` method of the
`ObjectController` changed API, taking a `ctrl` argument now (introduced
by the `timing_stats` decorator).
This commit adds the argument to 'our' `ObjectController` to restore
compatibility.

Fix `ObjectController` API-compatibility

---

.circleci/config.yml

Scheduled weekly func-tests run at 00:00 on Sunday, so that new blocking changes on the Openstack Swift master branch will give a red build till our code is updated

Scheduled weekly func-tests run in CircleCI
